export enum EventProgressPresentationEnum {
  FETCH_CONTENT_WIKIPEDIA = 'FETCH_CONTENT_WIKIPEDIA',
  READ_TEXT_USER = 'READ_TEXT_USER',
  CLEAN_TEXT = 'CLEAN_TEXT',
  SENTENCES_DETECTION = 'SENTENCES_DETECTION',
  IDENTIFYING_KEYWORDS = 'IDENTIFYING_KEYWORDS',
  SEARCHING_IMAGE = 'SEARCHING_IMAGE'
}
